// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceDeskDashboardApi.Context;

#nullable disable

namespace ServiceDeskDashboardApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ServiceDeskDashboardApi.Entities.WebHookReleaseCommitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CommitAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommitMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebHookReleaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WebHookReleaseId");

                    b.ToTable("WebHookReleaseCommit", "pbi");
                });

            modelBuilder.Entity("ServiceDeskDashboardApi.Entities.WebHookReleaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeployApproveMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeployApprovedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeployApproverUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeployCompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeployQueuedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeployReleaseDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("DeployReleaseDefinitionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeployReleaseEnvironmentId")
                        .HasColumnType("int");

                    b.Property<string>("DeployReleaseEnvironmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeployRequestedForUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeployRequstedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeployStartedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeploymentId")
                        .HasColumnType("int");

                    b.Property<int>("DeploymentReleaseId")
                        .HasColumnType("int");

                    b.Property<string>("DeploymentReleaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailedMessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("pbi.WebHookRelease", "pbi");
                });

            modelBuilder.Entity("ServiceDeskDashboardApi.Entities.WebHookReleaseCommitEntity", b =>
                {
                    b.HasOne("ServiceDeskDashboardApi.Entities.WebHookReleaseEntity", "WebHookRelease")
                        .WithMany("Commits")
                        .HasForeignKey("WebHookReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebHookRelease");
                });

            modelBuilder.Entity("ServiceDeskDashboardApi.Entities.WebHookReleaseEntity", b =>
                {
                    b.Navigation("Commits");
                });
#pragma warning restore 612, 618
        }
    }
}
